import avatar from '../assets/images/avatar.png';

export const employes = [{
  id: 0,
  isSubscribe: false,
  name: 'Прокофьева Ольга Васильевна',
  position: 'Программист',
  avatar: avatar,
  ad: '120/80',
  promille: 0.2,
  temp: 37.8,
},{
  id: 1,
  isSubscribe: false,
  name: 'Иванов Иван Иванович',
  position: 'Дизайнер',
  avatar: avatar,
  ad: '118/76',
  promille: 0.3,
  temp: 36.8,
},{
  id: 2,
  isSubscribe: false,
  name: 'Петров Иван Иванович',
  position: 'Дизайнер',
  avatar: avatar,
  ad: '118/76',
  promille: 0.3,
  temp: 36.8,
},{
  id: 3,
  isSubscribe: false,
  name: 'Сидоров Иван Иванович',
  position: 'Дизайнер',
  avatar: avatar,
  ad: '118/76',
  promille: 0.3,
  temp: 36.8,
},{
  id: 4,
  isSubscribe: false,
  name: 'Чебурашка Иван Иванович',
  position: 'Дизайнер',
  avatar: avatar,
  ad: '118/76',
  promille: 0.3,
  temp: 36.8,
}]
